name: sac

agent:
  firm_id: 5
  state_size: 3
  action_size: 20
  hidden_size: 64
  buffer_size: 10000
  batch_size: 64
  gamma: 0.99
  actor_lr: 0.0003
  critic_lr: 0.0003
  alpha_lr: 0.0003
  tau: 0.005
  update_every: 1
  gradient_steps: 1
  min_replay_size: 1000
  alpha: 0.05
  auto_entropy_tuning: false
  target_entropy: null
